[project]
name = "arxiv-follow"
version = "0.1.0"
description = "ArXiv论文监控系统 - 支持研究者跟踪、主题订阅和定期报告"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "openai>=1.54.0",
]
