"""
配置模块

包含系统配置参数和设置。
"""

from .settings import (
    RESEARCHERS_TSV_URL,
    DEFAULT_TOPICS,
    REQUEST_TIMEOUT,
    DISPLAY_LIMIT,
    DEFAULT_DAYS_BACK,
    REPORTS_DIR,
    DIDA_API_CONFIG,
    TRANSLATION_CONFIG,
    PAPER_ANALYSIS_CONFIG,
)

__all__ = [
    "RESEARCHERS_TSV_URL",
    "DEFAULT_TOPICS",
    "REQUEST_TIMEOUT", 
    "DISPLAY_LIMIT",
    "DEFAULT_DAYS_BACK",
    "REPORTS_DIR",
    "DIDA_API_CONFIG",
    "TRANSLATION_CONFIG",
    "PAPER_ANALYSIS_CONFIG",
] 